export const TIMEOUTS = {
  AUTH_BOOTSTRAP_MS: 4000,
  AUTH_REQUEST_MS: 1500,
  AUTH_ACTION_MS: 5000,
  REQUEST_MS: 7000,
  POEM_FETCH_MS: 7000,
  COMMENT_FETCH_MS: 7000,
  ADMIN_FETCH_MS: 7000,
  REQUEST_RETRY_BASE_DELAY_MS: 300,
  REQUEST_RETRY_MAX_DELAY_MS: 1200,
  ONLINE_RECOVERY_DELAY_MS: 250,
}

export const RETRY = {
  AUTH_RETRIES: 2,
  REQUEST_RETRIES: 2,
}

export const UI = {
  SUCCESS_MESSAGE_DURATION_MS: 4000,
}

export const API = {
  POEMS_TABLE: 'poems',
  COMMENTS_TABLE: 'comments',
}

export const VALIDATION = {
  MIN_TITLE_LENGTH: 1,
  MIN_CONTENT_LENGTH: 1,
  MIN_PREVIEW_LENGTH: 1,
  MAX_TITLE_LENGTH: 255,
  MAX_SLUG_LENGTH: 120,
  SLUG_PATTERN: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
  MIN_COMMENT_LENGTH: 1,
  MAX_COMMENT_LENGTH: 5000,
}
